//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34011
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34011.
// 
#pragma warning disable 1591

namespace IPC2Fase3QE.ServicioReferencia {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback conectarServidorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarSursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCodigoSedeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCodigoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCodigoDepartamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCodigoSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback existeclienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback getApellidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCodigoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCasillaClienteMaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCasillaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCasillaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNombreEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback getApellidoEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarCSVImpuestoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarCSVPaqueteOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarCSVEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback existeDirectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginDirectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNombreDirectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback getApellidoDiretorOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstadoEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback FacturaImagenOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NumeroEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TotalSueldosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::IPC2Fase3QE.Properties.Settings.Default.IPC2Fase2QE_ServicioReferencia_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event conectarServidorCompletedEventHandler conectarServidorCompleted;
        
        /// <remarks/>
        public event SeleccionarSursalCompletedEventHandler SeleccionarSursalCompleted;
        
        /// <remarks/>
        public event VerificarDepartamentoCompletedEventHandler VerificarDepartamentoCompleted;
        
        /// <remarks/>
        public event ObtenerCodigoSedeCompletedEventHandler ObtenerCodigoSedeCompleted;
        
        /// <remarks/>
        public event ObtenerCodigoClienteCompletedEventHandler ObtenerCodigoClienteCompleted;
        
        /// <remarks/>
        public event ObtenerCodigoDepartamentoCompletedEventHandler ObtenerCodigoDepartamentoCompleted;
        
        /// <remarks/>
        public event ObtenerCodigoSucursalCompletedEventHandler ObtenerCodigoSucursalCompleted;
        
        /// <remarks/>
        public event RegistrarCompletedEventHandler RegistrarCompleted;
        
        /// <remarks/>
        public event existeclienteCompletedEventHandler existeclienteCompleted;
        
        /// <remarks/>
        public event LoginClienteCompletedEventHandler LoginClienteCompleted;
        
        /// <remarks/>
        public event getNombreCompletedEventHandler getNombreCompleted;
        
        /// <remarks/>
        public event getApellidoCompletedEventHandler getApellidoCompleted;
        
        /// <remarks/>
        public event getCodigoClienteCompletedEventHandler getCodigoClienteCompleted;
        
        /// <remarks/>
        public event getCasillaClienteMaxCompletedEventHandler getCasillaClienteMaxCompleted;
        
        /// <remarks/>
        public event getCasillaClienteCompletedEventHandler getCasillaClienteCompleted;
        
        /// <remarks/>
        public event ModificarCasillaClienteCompletedEventHandler ModificarCasillaClienteCompleted;
        
        /// <remarks/>
        public event LoginEmpleadoCompletedEventHandler LoginEmpleadoCompleted;
        
        /// <remarks/>
        public event getNombreEmpCompletedEventHandler getNombreEmpCompleted;
        
        /// <remarks/>
        public event getApellidoEmpCompletedEventHandler getApellidoEmpCompleted;
        
        /// <remarks/>
        public event CargarCSVImpuestoCompletedEventHandler CargarCSVImpuestoCompleted;
        
        /// <remarks/>
        public event CargarCSVPaqueteCompletedEventHandler CargarCSVPaqueteCompleted;
        
        /// <remarks/>
        public event CargarCSVEmpleadoCompletedEventHandler CargarCSVEmpleadoCompleted;
        
        /// <remarks/>
        public event existeDirectorCompletedEventHandler existeDirectorCompleted;
        
        /// <remarks/>
        public event LoginDirectorCompletedEventHandler LoginDirectorCompleted;
        
        /// <remarks/>
        public event getNombreDirectorCompletedEventHandler getNombreDirectorCompleted;
        
        /// <remarks/>
        public event getApellidoDiretorCompletedEventHandler getApellidoDiretorCompleted;
        
        /// <remarks/>
        public event EstadoEmpleadoCompletedEventHandler EstadoEmpleadoCompleted;
        
        /// <remarks/>
        public event FacturaImagenCompletedEventHandler FacturaImagenCompleted;
        
        /// <remarks/>
        public event obtenerEmpleadoCompletedEventHandler obtenerEmpleadoCompleted;
        
        /// <remarks/>
        public event NumeroEmpleadoCompletedEventHandler NumeroEmpleadoCompleted;
        
        /// <remarks/>
        public event TotalSueldosCompletedEventHandler TotalSueldosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/conectarServidor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool conectarServidor() {
            object[] results = this.Invoke("conectarServidor", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void conectarServidorAsync() {
            this.conectarServidorAsync(null);
        }
        
        /// <remarks/>
        public void conectarServidorAsync(object userState) {
            if ((this.conectarServidorOperationCompleted == null)) {
                this.conectarServidorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconectarServidorOperationCompleted);
            }
            this.InvokeAsync("conectarServidor", new object[0], this.conectarServidorOperationCompleted, userState);
        }
        
        private void OnconectarServidorOperationCompleted(object arg) {
            if ((this.conectarServidorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.conectarServidorCompleted(this, new conectarServidorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarSursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SeleccionarSursal(string nombresucur) {
            object[] results = this.Invoke("SeleccionarSursal", new object[] {
                        nombresucur});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarSursalAsync(string nombresucur) {
            this.SeleccionarSursalAsync(nombresucur, null);
        }
        
        /// <remarks/>
        public void SeleccionarSursalAsync(string nombresucur, object userState) {
            if ((this.SeleccionarSursalOperationCompleted == null)) {
                this.SeleccionarSursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarSursalOperationCompleted);
            }
            this.InvokeAsync("SeleccionarSursal", new object[] {
                        nombresucur}, this.SeleccionarSursalOperationCompleted, userState);
        }
        
        private void OnSeleccionarSursalOperationCompleted(object arg) {
            if ((this.SeleccionarSursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarSursalCompleted(this, new SeleccionarSursalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VerificarDepartamento(string nombredepa, int sucur) {
            object[] results = this.Invoke("VerificarDepartamento", new object[] {
                        nombredepa,
                        sucur});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarDepartamentoAsync(string nombredepa, int sucur) {
            this.VerificarDepartamentoAsync(nombredepa, sucur, null);
        }
        
        /// <remarks/>
        public void VerificarDepartamentoAsync(string nombredepa, int sucur, object userState) {
            if ((this.VerificarDepartamentoOperationCompleted == null)) {
                this.VerificarDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDepartamentoOperationCompleted);
            }
            this.InvokeAsync("VerificarDepartamento", new object[] {
                        nombredepa,
                        sucur}, this.VerificarDepartamentoOperationCompleted, userState);
        }
        
        private void OnVerificarDepartamentoOperationCompleted(object arg) {
            if ((this.VerificarDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDepartamentoCompleted(this, new VerificarDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCodigoSede", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObtenerCodigoSede(string nombresede) {
            object[] results = this.Invoke("ObtenerCodigoSede", new object[] {
                        nombresede});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCodigoSedeAsync(string nombresede) {
            this.ObtenerCodigoSedeAsync(nombresede, null);
        }
        
        /// <remarks/>
        public void ObtenerCodigoSedeAsync(string nombresede, object userState) {
            if ((this.ObtenerCodigoSedeOperationCompleted == null)) {
                this.ObtenerCodigoSedeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCodigoSedeOperationCompleted);
            }
            this.InvokeAsync("ObtenerCodigoSede", new object[] {
                        nombresede}, this.ObtenerCodigoSedeOperationCompleted, userState);
        }
        
        private void OnObtenerCodigoSedeOperationCompleted(object arg) {
            if ((this.ObtenerCodigoSedeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCodigoSedeCompleted(this, new ObtenerCodigoSedeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCodigoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObtenerCodigoCliente(string nombrecliente) {
            object[] results = this.Invoke("ObtenerCodigoCliente", new object[] {
                        nombrecliente});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCodigoClienteAsync(string nombrecliente) {
            this.ObtenerCodigoClienteAsync(nombrecliente, null);
        }
        
        /// <remarks/>
        public void ObtenerCodigoClienteAsync(string nombrecliente, object userState) {
            if ((this.ObtenerCodigoClienteOperationCompleted == null)) {
                this.ObtenerCodigoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCodigoClienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerCodigoCliente", new object[] {
                        nombrecliente}, this.ObtenerCodigoClienteOperationCompleted, userState);
        }
        
        private void OnObtenerCodigoClienteOperationCompleted(object arg) {
            if ((this.ObtenerCodigoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCodigoClienteCompleted(this, new ObtenerCodigoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCodigoDepartamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObtenerCodigoDepartamento(string nombredepartamento) {
            object[] results = this.Invoke("ObtenerCodigoDepartamento", new object[] {
                        nombredepartamento});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCodigoDepartamentoAsync(string nombredepartamento) {
            this.ObtenerCodigoDepartamentoAsync(nombredepartamento, null);
        }
        
        /// <remarks/>
        public void ObtenerCodigoDepartamentoAsync(string nombredepartamento, object userState) {
            if ((this.ObtenerCodigoDepartamentoOperationCompleted == null)) {
                this.ObtenerCodigoDepartamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCodigoDepartamentoOperationCompleted);
            }
            this.InvokeAsync("ObtenerCodigoDepartamento", new object[] {
                        nombredepartamento}, this.ObtenerCodigoDepartamentoOperationCompleted, userState);
        }
        
        private void OnObtenerCodigoDepartamentoOperationCompleted(object arg) {
            if ((this.ObtenerCodigoDepartamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCodigoDepartamentoCompleted(this, new ObtenerCodigoDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCodigoSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObtenerCodigoSucursal(string nombresucursal) {
            object[] results = this.Invoke("ObtenerCodigoSucursal", new object[] {
                        nombresucursal});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCodigoSucursalAsync(string nombresucursal) {
            this.ObtenerCodigoSucursalAsync(nombresucursal, null);
        }
        
        /// <remarks/>
        public void ObtenerCodigoSucursalAsync(string nombresucursal, object userState) {
            if ((this.ObtenerCodigoSucursalOperationCompleted == null)) {
                this.ObtenerCodigoSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCodigoSucursalOperationCompleted);
            }
            this.InvokeAsync("ObtenerCodigoSucursal", new object[] {
                        nombresucursal}, this.ObtenerCodigoSucursalOperationCompleted, userState);
        }
        
        private void OnObtenerCodigoSucursalOperationCompleted(object arg) {
            if ((this.ObtenerCodigoSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCodigoSucursalCompleted(this, new ObtenerCodigoSucursalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Registrar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Registrar(string tabla, string campos, string valor) {
            object[] results = this.Invoke("Registrar", new object[] {
                        tabla,
                        campos,
                        valor});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarAsync(string tabla, string campos, string valor) {
            this.RegistrarAsync(tabla, campos, valor, null);
        }
        
        /// <remarks/>
        public void RegistrarAsync(string tabla, string campos, string valor, object userState) {
            if ((this.RegistrarOperationCompleted == null)) {
                this.RegistrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarOperationCompleted);
            }
            this.InvokeAsync("Registrar", new object[] {
                        tabla,
                        campos,
                        valor}, this.RegistrarOperationCompleted, userState);
        }
        
        private void OnRegistrarOperationCompleted(object arg) {
            if ((this.RegistrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarCompleted(this, new RegistrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/existecliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool existecliente(string user) {
            object[] results = this.Invoke("existecliente", new object[] {
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void existeclienteAsync(string user) {
            this.existeclienteAsync(user, null);
        }
        
        /// <remarks/>
        public void existeclienteAsync(string user, object userState) {
            if ((this.existeclienteOperationCompleted == null)) {
                this.existeclienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexisteclienteOperationCompleted);
            }
            this.InvokeAsync("existecliente", new object[] {
                        user}, this.existeclienteOperationCompleted, userState);
        }
        
        private void OnexisteclienteOperationCompleted(object arg) {
            if ((this.existeclienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existeclienteCompleted(this, new existeclienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LoginCliente(string user, string contraseña, string rol) {
            object[] results = this.Invoke("LoginCliente", new object[] {
                        user,
                        contraseña,
                        rol});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginClienteAsync(string user, string contraseña, string rol) {
            this.LoginClienteAsync(user, contraseña, rol, null);
        }
        
        /// <remarks/>
        public void LoginClienteAsync(string user, string contraseña, string rol, object userState) {
            if ((this.LoginClienteOperationCompleted == null)) {
                this.LoginClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginClienteOperationCompleted);
            }
            this.InvokeAsync("LoginCliente", new object[] {
                        user,
                        contraseña,
                        rol}, this.LoginClienteOperationCompleted, userState);
        }
        
        private void OnLoginClienteOperationCompleted(object arg) {
            if ((this.LoginClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginClienteCompleted(this, new LoginClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNombre(string user) {
            object[] results = this.Invoke("getNombre", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNombreAsync(string user) {
            this.getNombreAsync(user, null);
        }
        
        /// <remarks/>
        public void getNombreAsync(string user, object userState) {
            if ((this.getNombreOperationCompleted == null)) {
                this.getNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNombreOperationCompleted);
            }
            this.InvokeAsync("getNombre", new object[] {
                        user}, this.getNombreOperationCompleted, userState);
        }
        
        private void OngetNombreOperationCompleted(object arg) {
            if ((this.getNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNombreCompleted(this, new getNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getApellido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getApellido(string user) {
            object[] results = this.Invoke("getApellido", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getApellidoAsync(string user) {
            this.getApellidoAsync(user, null);
        }
        
        /// <remarks/>
        public void getApellidoAsync(string user, object userState) {
            if ((this.getApellidoOperationCompleted == null)) {
                this.getApellidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApellidoOperationCompleted);
            }
            this.InvokeAsync("getApellido", new object[] {
                        user}, this.getApellidoOperationCompleted, userState);
        }
        
        private void OngetApellidoOperationCompleted(object arg) {
            if ((this.getApellidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getApellidoCompleted(this, new getApellidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCodigoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCodigoCliente(string user) {
            object[] results = this.Invoke("getCodigoCliente", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCodigoClienteAsync(string user) {
            this.getCodigoClienteAsync(user, null);
        }
        
        /// <remarks/>
        public void getCodigoClienteAsync(string user, object userState) {
            if ((this.getCodigoClienteOperationCompleted == null)) {
                this.getCodigoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCodigoClienteOperationCompleted);
            }
            this.InvokeAsync("getCodigoCliente", new object[] {
                        user}, this.getCodigoClienteOperationCompleted, userState);
        }
        
        private void OngetCodigoClienteOperationCompleted(object arg) {
            if ((this.getCodigoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCodigoClienteCompleted(this, new getCodigoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCasillaClienteMax", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCasillaClienteMax() {
            object[] results = this.Invoke("getCasillaClienteMax", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCasillaClienteMaxAsync() {
            this.getCasillaClienteMaxAsync(null);
        }
        
        /// <remarks/>
        public void getCasillaClienteMaxAsync(object userState) {
            if ((this.getCasillaClienteMaxOperationCompleted == null)) {
                this.getCasillaClienteMaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCasillaClienteMaxOperationCompleted);
            }
            this.InvokeAsync("getCasillaClienteMax", new object[0], this.getCasillaClienteMaxOperationCompleted, userState);
        }
        
        private void OngetCasillaClienteMaxOperationCompleted(object arg) {
            if ((this.getCasillaClienteMaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCasillaClienteMaxCompleted(this, new getCasillaClienteMaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCasillaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCasillaCliente(string user) {
            object[] results = this.Invoke("getCasillaCliente", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCasillaClienteAsync(string user) {
            this.getCasillaClienteAsync(user, null);
        }
        
        /// <remarks/>
        public void getCasillaClienteAsync(string user, object userState) {
            if ((this.getCasillaClienteOperationCompleted == null)) {
                this.getCasillaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCasillaClienteOperationCompleted);
            }
            this.InvokeAsync("getCasillaCliente", new object[] {
                        user}, this.getCasillaClienteOperationCompleted, userState);
        }
        
        private void OngetCasillaClienteOperationCompleted(object arg) {
            if ((this.getCasillaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCasillaClienteCompleted(this, new getCasillaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCasillaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ModificarCasillaCliente(int cod, string casilla) {
            object[] results = this.Invoke("ModificarCasillaCliente", new object[] {
                        cod,
                        casilla});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarCasillaClienteAsync(int cod, string casilla) {
            this.ModificarCasillaClienteAsync(cod, casilla, null);
        }
        
        /// <remarks/>
        public void ModificarCasillaClienteAsync(int cod, string casilla, object userState) {
            if ((this.ModificarCasillaClienteOperationCompleted == null)) {
                this.ModificarCasillaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCasillaClienteOperationCompleted);
            }
            this.InvokeAsync("ModificarCasillaCliente", new object[] {
                        cod,
                        casilla}, this.ModificarCasillaClienteOperationCompleted, userState);
        }
        
        private void OnModificarCasillaClienteOperationCompleted(object arg) {
            if ((this.ModificarCasillaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCasillaClienteCompleted(this, new ModificarCasillaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoginEmpleado(string usuario, string contraseña, string rol) {
            object[] results = this.Invoke("LoginEmpleado", new object[] {
                        usuario,
                        contraseña,
                        rol});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginEmpleadoAsync(string usuario, string contraseña, string rol) {
            this.LoginEmpleadoAsync(usuario, contraseña, rol, null);
        }
        
        /// <remarks/>
        public void LoginEmpleadoAsync(string usuario, string contraseña, string rol, object userState) {
            if ((this.LoginEmpleadoOperationCompleted == null)) {
                this.LoginEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginEmpleadoOperationCompleted);
            }
            this.InvokeAsync("LoginEmpleado", new object[] {
                        usuario,
                        contraseña,
                        rol}, this.LoginEmpleadoOperationCompleted, userState);
        }
        
        private void OnLoginEmpleadoOperationCompleted(object arg) {
            if ((this.LoginEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginEmpleadoCompleted(this, new LoginEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNombreEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNombreEmp(string user) {
            object[] results = this.Invoke("getNombreEmp", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNombreEmpAsync(string user) {
            this.getNombreEmpAsync(user, null);
        }
        
        /// <remarks/>
        public void getNombreEmpAsync(string user, object userState) {
            if ((this.getNombreEmpOperationCompleted == null)) {
                this.getNombreEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNombreEmpOperationCompleted);
            }
            this.InvokeAsync("getNombreEmp", new object[] {
                        user}, this.getNombreEmpOperationCompleted, userState);
        }
        
        private void OngetNombreEmpOperationCompleted(object arg) {
            if ((this.getNombreEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNombreEmpCompleted(this, new getNombreEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getApellidoEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getApellidoEmp(string user) {
            object[] results = this.Invoke("getApellidoEmp", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getApellidoEmpAsync(string user) {
            this.getApellidoEmpAsync(user, null);
        }
        
        /// <remarks/>
        public void getApellidoEmpAsync(string user, object userState) {
            if ((this.getApellidoEmpOperationCompleted == null)) {
                this.getApellidoEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApellidoEmpOperationCompleted);
            }
            this.InvokeAsync("getApellidoEmp", new object[] {
                        user}, this.getApellidoEmpOperationCompleted, userState);
        }
        
        private void OngetApellidoEmpOperationCompleted(object arg) {
            if ((this.getApellidoEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getApellidoEmpCompleted(this, new getApellidoEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarCSVImpuesto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CargarCSVImpuesto(string path) {
            object[] results = this.Invoke("CargarCSVImpuesto", new object[] {
                        path});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CargarCSVImpuestoAsync(string path) {
            this.CargarCSVImpuestoAsync(path, null);
        }
        
        /// <remarks/>
        public void CargarCSVImpuestoAsync(string path, object userState) {
            if ((this.CargarCSVImpuestoOperationCompleted == null)) {
                this.CargarCSVImpuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarCSVImpuestoOperationCompleted);
            }
            this.InvokeAsync("CargarCSVImpuesto", new object[] {
                        path}, this.CargarCSVImpuestoOperationCompleted, userState);
        }
        
        private void OnCargarCSVImpuestoOperationCompleted(object arg) {
            if ((this.CargarCSVImpuestoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarCSVImpuestoCompleted(this, new CargarCSVImpuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarCSVPaquete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CargarCSVPaquete(string path) {
            object[] results = this.Invoke("CargarCSVPaquete", new object[] {
                        path});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CargarCSVPaqueteAsync(string path) {
            this.CargarCSVPaqueteAsync(path, null);
        }
        
        /// <remarks/>
        public void CargarCSVPaqueteAsync(string path, object userState) {
            if ((this.CargarCSVPaqueteOperationCompleted == null)) {
                this.CargarCSVPaqueteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarCSVPaqueteOperationCompleted);
            }
            this.InvokeAsync("CargarCSVPaquete", new object[] {
                        path}, this.CargarCSVPaqueteOperationCompleted, userState);
        }
        
        private void OnCargarCSVPaqueteOperationCompleted(object arg) {
            if ((this.CargarCSVPaqueteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarCSVPaqueteCompleted(this, new CargarCSVPaqueteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarCSVEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CargarCSVEmpleado(string path) {
            object[] results = this.Invoke("CargarCSVEmpleado", new object[] {
                        path});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CargarCSVEmpleadoAsync(string path) {
            this.CargarCSVEmpleadoAsync(path, null);
        }
        
        /// <remarks/>
        public void CargarCSVEmpleadoAsync(string path, object userState) {
            if ((this.CargarCSVEmpleadoOperationCompleted == null)) {
                this.CargarCSVEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarCSVEmpleadoOperationCompleted);
            }
            this.InvokeAsync("CargarCSVEmpleado", new object[] {
                        path}, this.CargarCSVEmpleadoOperationCompleted, userState);
        }
        
        private void OnCargarCSVEmpleadoOperationCompleted(object arg) {
            if ((this.CargarCSVEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarCSVEmpleadoCompleted(this, new CargarCSVEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/existeDirector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool existeDirector(string user) {
            object[] results = this.Invoke("existeDirector", new object[] {
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void existeDirectorAsync(string user) {
            this.existeDirectorAsync(user, null);
        }
        
        /// <remarks/>
        public void existeDirectorAsync(string user, object userState) {
            if ((this.existeDirectorOperationCompleted == null)) {
                this.existeDirectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexisteDirectorOperationCompleted);
            }
            this.InvokeAsync("existeDirector", new object[] {
                        user}, this.existeDirectorOperationCompleted, userState);
        }
        
        private void OnexisteDirectorOperationCompleted(object arg) {
            if ((this.existeDirectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existeDirectorCompleted(this, new existeDirectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginDirector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LoginDirector(string user, string contraseña, string rol) {
            object[] results = this.Invoke("LoginDirector", new object[] {
                        user,
                        contraseña,
                        rol});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginDirectorAsync(string user, string contraseña, string rol) {
            this.LoginDirectorAsync(user, contraseña, rol, null);
        }
        
        /// <remarks/>
        public void LoginDirectorAsync(string user, string contraseña, string rol, object userState) {
            if ((this.LoginDirectorOperationCompleted == null)) {
                this.LoginDirectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginDirectorOperationCompleted);
            }
            this.InvokeAsync("LoginDirector", new object[] {
                        user,
                        contraseña,
                        rol}, this.LoginDirectorOperationCompleted, userState);
        }
        
        private void OnLoginDirectorOperationCompleted(object arg) {
            if ((this.LoginDirectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginDirectorCompleted(this, new LoginDirectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNombreDirector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNombreDirector(string user) {
            object[] results = this.Invoke("getNombreDirector", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNombreDirectorAsync(string user) {
            this.getNombreDirectorAsync(user, null);
        }
        
        /// <remarks/>
        public void getNombreDirectorAsync(string user, object userState) {
            if ((this.getNombreDirectorOperationCompleted == null)) {
                this.getNombreDirectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNombreDirectorOperationCompleted);
            }
            this.InvokeAsync("getNombreDirector", new object[] {
                        user}, this.getNombreDirectorOperationCompleted, userState);
        }
        
        private void OngetNombreDirectorOperationCompleted(object arg) {
            if ((this.getNombreDirectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNombreDirectorCompleted(this, new getNombreDirectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getApellidoDiretor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getApellidoDiretor(string user) {
            object[] results = this.Invoke("getApellidoDiretor", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getApellidoDiretorAsync(string user) {
            this.getApellidoDiretorAsync(user, null);
        }
        
        /// <remarks/>
        public void getApellidoDiretorAsync(string user, object userState) {
            if ((this.getApellidoDiretorOperationCompleted == null)) {
                this.getApellidoDiretorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApellidoDiretorOperationCompleted);
            }
            this.InvokeAsync("getApellidoDiretor", new object[] {
                        user}, this.getApellidoDiretorOperationCompleted, userState);
        }
        
        private void OngetApellidoDiretorOperationCompleted(object arg) {
            if ((this.getApellidoDiretorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getApellidoDiretorCompleted(this, new getApellidoDiretorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EstadoEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EstadoEmpleado(int CodEmpleado, string Estado) {
            object[] results = this.Invoke("EstadoEmpleado", new object[] {
                        CodEmpleado,
                        Estado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EstadoEmpleadoAsync(int CodEmpleado, string Estado) {
            this.EstadoEmpleadoAsync(CodEmpleado, Estado, null);
        }
        
        /// <remarks/>
        public void EstadoEmpleadoAsync(int CodEmpleado, string Estado, object userState) {
            if ((this.EstadoEmpleadoOperationCompleted == null)) {
                this.EstadoEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstadoEmpleadoOperationCompleted);
            }
            this.InvokeAsync("EstadoEmpleado", new object[] {
                        CodEmpleado,
                        Estado}, this.EstadoEmpleadoOperationCompleted, userState);
        }
        
        private void OnEstadoEmpleadoOperationCompleted(object arg) {
            if ((this.EstadoEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstadoEmpleadoCompleted(this, new EstadoEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FacturaImagen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FacturaImagen(string CodCliente, string link) {
            object[] results = this.Invoke("FacturaImagen", new object[] {
                        CodCliente,
                        link});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FacturaImagenAsync(string CodCliente, string link) {
            this.FacturaImagenAsync(CodCliente, link, null);
        }
        
        /// <remarks/>
        public void FacturaImagenAsync(string CodCliente, string link, object userState) {
            if ((this.FacturaImagenOperationCompleted == null)) {
                this.FacturaImagenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFacturaImagenOperationCompleted);
            }
            this.InvokeAsync("FacturaImagen", new object[] {
                        CodCliente,
                        link}, this.FacturaImagenOperationCompleted, userState);
        }
        
        private void OnFacturaImagenOperationCompleted(object arg) {
            if ((this.FacturaImagenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FacturaImagenCompleted(this, new FacturaImagenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerEmpleado(string nombre, int sucu) {
            object[] results = this.Invoke("obtenerEmpleado", new object[] {
                        nombre,
                        sucu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEmpleadoAsync(string nombre, int sucu) {
            this.obtenerEmpleadoAsync(nombre, sucu, null);
        }
        
        /// <remarks/>
        public void obtenerEmpleadoAsync(string nombre, int sucu, object userState) {
            if ((this.obtenerEmpleadoOperationCompleted == null)) {
                this.obtenerEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEmpleadoOperationCompleted);
            }
            this.InvokeAsync("obtenerEmpleado", new object[] {
                        nombre,
                        sucu}, this.obtenerEmpleadoOperationCompleted, userState);
        }
        
        private void OnobtenerEmpleadoOperationCompleted(object arg) {
            if ((this.obtenerEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEmpleadoCompleted(this, new obtenerEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NumeroEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NumeroEmpleado(string nombre, int sucu) {
            object[] results = this.Invoke("NumeroEmpleado", new object[] {
                        nombre,
                        sucu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NumeroEmpleadoAsync(string nombre, int sucu) {
            this.NumeroEmpleadoAsync(nombre, sucu, null);
        }
        
        /// <remarks/>
        public void NumeroEmpleadoAsync(string nombre, int sucu, object userState) {
            if ((this.NumeroEmpleadoOperationCompleted == null)) {
                this.NumeroEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNumeroEmpleadoOperationCompleted);
            }
            this.InvokeAsync("NumeroEmpleado", new object[] {
                        nombre,
                        sucu}, this.NumeroEmpleadoOperationCompleted, userState);
        }
        
        private void OnNumeroEmpleadoOperationCompleted(object arg) {
            if ((this.NumeroEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NumeroEmpleadoCompleted(this, new NumeroEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TotalSueldos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TotalSueldos(string nombre, int sucu) {
            object[] results = this.Invoke("TotalSueldos", new object[] {
                        nombre,
                        sucu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TotalSueldosAsync(string nombre, int sucu) {
            this.TotalSueldosAsync(nombre, sucu, null);
        }
        
        /// <remarks/>
        public void TotalSueldosAsync(string nombre, int sucu, object userState) {
            if ((this.TotalSueldosOperationCompleted == null)) {
                this.TotalSueldosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTotalSueldosOperationCompleted);
            }
            this.InvokeAsync("TotalSueldos", new object[] {
                        nombre,
                        sucu}, this.TotalSueldosOperationCompleted, userState);
        }
        
        private void OnTotalSueldosOperationCompleted(object arg) {
            if ((this.TotalSueldosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TotalSueldosCompleted(this, new TotalSueldosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void conectarServidorCompletedEventHandler(object sender, conectarServidorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class conectarServidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal conectarServidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SeleccionarSursalCompletedEventHandler(object sender, SeleccionarSursalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarSursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarSursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void VerificarDepartamentoCompletedEventHandler(object sender, VerificarDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ObtenerCodigoSedeCompletedEventHandler(object sender, ObtenerCodigoSedeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCodigoSedeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCodigoSedeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ObtenerCodigoClienteCompletedEventHandler(object sender, ObtenerCodigoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCodigoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCodigoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ObtenerCodigoDepartamentoCompletedEventHandler(object sender, ObtenerCodigoDepartamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCodigoDepartamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCodigoDepartamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ObtenerCodigoSucursalCompletedEventHandler(object sender, ObtenerCodigoSucursalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCodigoSucursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCodigoSucursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RegistrarCompletedEventHandler(object sender, RegistrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void existeclienteCompletedEventHandler(object sender, existeclienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existeclienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existeclienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LoginClienteCompletedEventHandler(object sender, LoginClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getNombreCompletedEventHandler(object sender, getNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getApellidoCompletedEventHandler(object sender, getApellidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getApellidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getApellidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getCodigoClienteCompletedEventHandler(object sender, getCodigoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCodigoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCodigoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getCasillaClienteMaxCompletedEventHandler(object sender, getCasillaClienteMaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCasillaClienteMaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCasillaClienteMaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getCasillaClienteCompletedEventHandler(object sender, getCasillaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCasillaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCasillaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ModificarCasillaClienteCompletedEventHandler(object sender, ModificarCasillaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarCasillaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarCasillaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LoginEmpleadoCompletedEventHandler(object sender, LoginEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getNombreEmpCompletedEventHandler(object sender, getNombreEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNombreEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNombreEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getApellidoEmpCompletedEventHandler(object sender, getApellidoEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getApellidoEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getApellidoEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CargarCSVImpuestoCompletedEventHandler(object sender, CargarCSVImpuestoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarCSVImpuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarCSVImpuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CargarCSVPaqueteCompletedEventHandler(object sender, CargarCSVPaqueteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarCSVPaqueteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarCSVPaqueteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CargarCSVEmpleadoCompletedEventHandler(object sender, CargarCSVEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarCSVEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarCSVEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void existeDirectorCompletedEventHandler(object sender, existeDirectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existeDirectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existeDirectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LoginDirectorCompletedEventHandler(object sender, LoginDirectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginDirectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginDirectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getNombreDirectorCompletedEventHandler(object sender, getNombreDirectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNombreDirectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNombreDirectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getApellidoDiretorCompletedEventHandler(object sender, getApellidoDiretorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getApellidoDiretorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getApellidoDiretorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void EstadoEmpleadoCompletedEventHandler(object sender, EstadoEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstadoEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstadoEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void FacturaImagenCompletedEventHandler(object sender, FacturaImagenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FacturaImagenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FacturaImagenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void obtenerEmpleadoCompletedEventHandler(object sender, obtenerEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void NumeroEmpleadoCompletedEventHandler(object sender, NumeroEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NumeroEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NumeroEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TotalSueldosCompletedEventHandler(object sender, TotalSueldosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TotalSueldosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TotalSueldosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591